package:
  name: cpptraj
#  version 0.1   trying to adapt recipe from AmberClassic
#  version 0.2   small tweaks get allow osx-64 build
  version: 0.2

source:
  path: ../
  
build:
  number: 0

requirements:
  build:
   - make
   - {{ compiler('fortran') }}
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
#  - {{ mpi }} # [ mpi == "mpich" ]
#  - {{ compiler('nvcc') }} # [ linux and not aarch64 ]
#  - coreutils
   - llvm-openmp  # [osx]
   - libgomp      # [linux and not aarch64]
   - fftw
   - openblas
   - arpack
   - openmm
#  - readline
   - libnetcdf
   - netcdf-fortran
#  - libboost-devel

  host:
#  - libboost-devel
   - openblas
   - arpack
   - openmm
   - libnetcdf
   - netcdf-fortran
   - llvm-openmp  # [osx]
   - libgomp      # [linux and not aarch64]
#  - {{ mpi }} # [ mpi == "mpich" ]
   - fftw
#  - readline

  run:
#  - libboost-devel
   - llvm-openmp  # [osx]
   - libgomp      # [linux and not aarch64]
   - openblas
   - arpack
   - openmm
   - libnetcdf
   - netcdf-fortran
#  - {{ mpi }} # [ mpi == "mpich" ]
   - fftw
#  - readline

about:
    home: https://github.com/Amber-MD/cpptraj.git
    license: GNU General Public License (GPL)
    license_file: 
       - LICENSE
    summary: 'Performs analysis of MD trajectories, especially for biomolecules'

