channels:
    - conda-forge
dependencies:
    - python=3.12
    - pyflakes
    - numpy=2.2.1
    - cython=0.29.36
    - setuptools
    - pytest
    - mock
    - curl
    - gcc_linux-64
    - gxx_linux-64
    - gfortran_linux-64
    - netcdf4
    - fftw
