#!/bin/bash

. ../MasterTest.sh

# Clean
CleanFiles ptraj_netcdf.in trajectory.netcdf trajectory_test.mdcrd \
            trajectory_nc4.mdcrd trajectory.nc4 \
            compress.mdcrd compress.nc4 \
            icompress.mdcrd icompress.nc4

TESTNAME='NetCDF tests'
Requires netcdf pnetcdf maxthreads 10

# Convert MDCRD to NETCDF and back again.
INPUT="ptraj_netcdf.in"
TOP="../tz2.truncoct.parm7"

cat > $INPUT <<EOF
trajin ../tz2.truncoct.crd
trajout trajectory.netcdf netcdf
EOF
RunCpptraj "Convert mdcrd -> NetCDF"
cat > $INPUT <<EOF
trajin trajectory.netcdf
trajout trajectory_test.mdcrd title "trajectory generated by ptraj"
EOF
RunCpptraj "Convert NetCDF -> mdcrd"
DoTest ../tz2.truncoct.crd trajectory_test.mdcrd

# NetCDF4/HDF5
UNITNAME='NetCDF4/HDF5 tests'
CheckFor hdf5
if [ $? -eq 0 ] ; then
  cat > $INPUT <<EOF
trajin ../tz2.truncoct.crd
trajout trajectory.nc4 netcdf hdf5
EOF
  RunCpptraj "Convert mdcrd -> NetCDF4/HDF5"
  cat > $INPUT <<EOF
trajin trajectory.nc4
trajout trajectory_nc4.mdcrd title "trajectory generated by ptraj"
EOF
  RunCpptraj "Convert NetCDF4/HDF5 -> mdcrd"
  DoTest ../tz2.truncoct.crd trajectory_nc4.mdcrd

  cat > $INPUT <<EOF
trajin ../tz2.truncoct.crd
trajout compress.nc4 netcdf hdf5 compress
EOF
  RunCpptraj "Convert mdcrd ->NetCDF4/HDF5 with compression"
  cat > $INPUT <<EOF
trajin compress.nc4
trajout compress.mdcrd title "trajectory generated by ptraj"
EOF
  RunCpptraj "Convert compressed NetCDF4/HDF5 -> mdcrd"
  DoTest ../tz2.truncoct.crd compress.mdcrd

  cat > $INPUT <<EOF
trajin ../tz2.truncoct.crd
trajout icompress.nc4 netcdf hdf5 icompress
EOF
  RunCpptraj "Convert mdcrd ->NetCDF4/HDF5 with lossy compression"
  cat > $INPUT <<EOF
trajin icompress.nc4
trajout icompress.mdcrd title "trajectory generated by ptraj"
EOF
  RunCpptraj "Convert lossy compressed NetCDF4/HDF5 -> mdcrd"
  # NOTE: An absolute tolerance of 0.0001 (which is greater than the
  #       possible precision of MDCRD format) is used to allow for
  #       the fact that a -0.000 will be converted to 0.000 by the
  #       lossy compression.
  DoTest ../tz2.truncoct.crd icompress.mdcrd -a 0.0001

fi

EndTest

exit 0
