# Parts of the build system that happen after enable_language()

include(TargetArch)
include(CheckFunctionExists)
include(CheckFortranFunctionExists)
include(CheckIncludeFile)
include(CheckIncludeFileCXX)
include(CheckCCompilerFlag)
include(CheckCXXCompilerFlag)
include(CheckLinkerFlag)
include(CheckSymbolExists)
include(CheckConstantExists)
include(CheckTypeSize)
include(TryLinkLibrary)

include(LibraryTracking)
include(BuildReport)
include(CompilationOptions)
include(RPATHConfig)
include(CopyTarget)
include(LibraryUtils)
