#!/bin/bash

. ../MasterTest.sh

CleanFiles ptraj.in cpptraj.nc mop.trr temp.crd total?.out

INPUT="-i ptraj.in"

GmxTrrRead() {
  TESTNAME='TRR force/velocity read/write'
  MaxThreads 2 "$TESTNAME"
  CheckNetcdf "$TESTNAME"
  CheckPnetcdf "$TESTNAME"
  if [ $CHECKERR -ne 0 ] ; then
    SkipCheck "$TESTNAME"
  else
      cat > ptraj.in <<EOF
parm nvt.protein.mol2
trajin nvt.2frame.trr
trajout cpptraj.nc
EOF
      RunCpptraj "TRR coords/force/velocity read test"
      NcTest cpptraj.nc.save cpptraj.nc
  fi
}

GmxTrrWrite() {
  cat > ptraj.in <<EOF
parm ../tz2.truncoct.parm7
trajin ../tz2.truncoct.crd
trajout mop.trr trr
EOF
  RunCpptraj "CRD => TRR"

  cat > ptraj.in <<EOF
parm ../tz2.truncoct.parm7
#trajin temp.trr
trajin mop.trr
trajout temp.crd title "trajectory generated by ptraj"
EOF
  RunCpptraj "TRR => CRD"
  DoTest ../tz2.truncoct.crd temp.crd
}

# Gromacs TRR append
GmxTrrAppend() {
  NotParallel "GMX TRR append"
  if [ $? -ne 0 ] ; then
    SkipCheck "GMX TRR append"
  else
    cat > ptraj.in <<EOF
parm ../tz2.truncoct.parm7
trajin ../tz2.truncoct.crd 1 5
trajout mop.trr trr
EOF
    RunCpptraj "CRD(1-5) => TRR"
    cat > ptraj.in <<EOF
parm ../tz2.truncoct.parm7
trajin ../tz2.truncoct.crd 6 10
trajout mop.trr trr append
EOF
    RunCpptraj "CRD(6-10) => TRR"
    cat > ptraj.in <<EOF
parm ../tz2.truncoct.parm7
trajin mop.trr
trajout temp.crd title "trajectory generated by ptraj"
EOF
    RunCpptraj "TRR (appended) => CRD"
    DoTest ../tz2.truncoct.crd temp.crd
  fi
}

# Gromacs TRR with offsets
GmxOffset() {
  MaxThreads 5 "GMX offset test"
  if [ $? -ne 0 ] ; then
    SkipCheck "GMX offset test"
  else
    cat > ptraj.in <<EOF
parm ../tz2.truncoct.parm7
trajin ../tz2.truncoct.crd 2 10 2
trajout total1.out title "offset test"
EOF
    RunCpptraj "GMX: CRD with offset"
    cat > ptraj.in <<EOF
parm ../tz2.truncoct.parm7
trajin mop.trr 2 10 2
trajout total2.out title "offset test"
EOF
    RunCpptraj "GMX: TRR with offset"
    DoTest total1.out total2.out
  fi
}

GmxTrrRead
GmxTrrWrite
GmxTrrAppend
GmxOffset

EndTest
exit 0
