#!/bin/bash

. ../MasterTest.sh

CleanFiles runavg.in runavg.crd R1.dat
CheckNetcdf
INPUT="runavg.in"
TOP="../tz2.parm7"
if [[ -z $DO_PARALLEL ]] ; then
  cat > $INPUT <<EOF
trajin ../tz2.nc 1 14
runavg window 5
trajout runavg.crd nobox title "trajectory generated by ptraj"
EOF
  RunCpptraj "Coordinate Running Average"
  DoTest runavg.crd.save runavg.crd
else
  cat > $INPUT <<EOF
trajin ../tz2.nc
runavg window 5
rms R1 :1-13&!@H= out R1.dat
EOF
  RunCpptraj "Coordinate Running Average (parallel)"
  DoTest R1.dat.save R1.dat
fi
EndTest

exit 0
