#!/bin/bash

. ../MasterTest.sh

CleanFiles runavg.in runavg.crd
CheckNetcdf
INPUT="runavg.in"
TOP="../tz2.parm7"
cat > $INPUT <<EOF
trajin ../tz2.nc 1 14
runavg window 5
trajout runavg.crd nobox title "trajectory generated by ptraj"
EOF

#CPPTRAJ=`which ptraj`
RunCpptraj "Coordinate Running Average"
DoTest runavg.crd.save runavg.crd
CheckTest
EndTest

exit 0
