#ifndef CPPTRAJ_VERSION_STRING
#define CPPTRAJ_VERSION_STRING "V14.03b"
#endif
#ifndef NETCDF_VERSION_STRING
#define NETCDF_VERSION_STRING "V13.0"
#define NETCDF_VERSION_STRLEN 5
#endif
#ifndef CPPTRAJ_INTERNAL_VERSION
#define CPPTRAJ_INTERNAL_VERSION "V4.0.4"
#endif
