#ifndef CPPTRAJ_VERSION_STRING
#define CPPTRAJ_VERSION_STRING "V18.00b"
/// This is used in NetcdfFile
#define CPPTRAJ_VERSION_STRLEN 7
#endif
#ifndef CPPTRAJ_INTERNAL_VERSION
#define CPPTRAJ_INTERNAL_VERSION "V4.3.5"
#endif
